[package]
name = "pedersen-hash"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.4.0"
ark-std = "0.4.0"
clap = { version = "4.5.1", features = ["derive", "string"] }
inquire = "0.7.5"
num = "0.4.3"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
